// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {filterHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lQ`QPOOO!oQPO'#CfO#fQPO'#CgOOQO'#Cp'#CpO$]QPO'#CpO$eQPO'#ChOOQO'#Ck'#CkOOQO'#Cl'#ClQ`QPOOOOQO,59[,59[O$eQPO,59SOOQO'#Cj'#CjO%SQPO,59SOOQO-E6j-E6jO%SQPO1G.nOOQO'#Cf'#CfOOQO'#Cg'#CgO%cQPO'#CpOOQO1G.n1G.nOOQO7+$Y7+$Y",
  stateData: "%v~OcOSPOSQOSROS~OTROUROVROWROXSOePOfQOpUOqUOrUO~Og]Xh]Xi]Xj]Xk]Xl]Xm]Xn]Xo]X~OTYXUYXVYXWYXXYXaYXeYXfYXpYXqYXrYX~P!QOTZXUZXVZXWZXXZXaZXeZXfZXpZXqZXrZX~P!QOePOfQO~OgZOhZOiZOjZOkZOlZOmZOnZOoZO~OTROUROVROWROXaOe_Of`O~OTrqpWUPXVf~",
  goto: "!cePPPPPPPPPPffpt{p!RPPP!XWROW[^TXSaTVOWSTOWRYSQ[TR^YQWOR]WSVOWQb[Rc^",
  nodeNames: "⚠ LineComment ( ) Filter True False Null Number Minus String Text Comparison Comparable CompareOp LogicOp",
  maxTerm: 34,
  nodeProps: [
    ["isolate", -3,10,11,13,""]
  ],
  propSources: [filterHighlighting],
  skippedNodes: [0,1,2,3],
  repeatNodeCount: 1,
  tokenData: "7X~RnXY#PYZ#P]^#Ppq#Pqr#Urs#itu$|xy%hyz%m}!O%r!P!Q$|!Q!R&i!R!['w![!](Y!^!_(_!_!`(l!`!a(y!c!d)W!d!p$|!p!q+W!q!r-W!r!}$|#R#S$|#T#Y$|#Y#Z.f#Z#b$|#b#c1u#c#h$|#h#i4g#i#o$|~#UOc~~#XQ!_!`#_#r#s#d~#dOh~~#iOn~~#lWpq#iqr#irs$Us#O#i#O#P$Z#P;'S#i;'S;=`$v<%lO#i~$ZOe~~$^Wrs#i!P!Q#i#O#P#i#U#V#i#Y#Z#i#b#c#i#f#g#i#h#i#i~$yP;=`<%l#i~%RVf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~%mOQ~~%rOR~~%wRX~}!O&Q!Q!R&i!R!['w~&VSP~OY&QZ;'S&Q;'S;=`&c<%lO&Q~&fP;=`<%l&Q~&nRW~!O!P&w!g!h']#X#Y']~&zP!Q![&}~'SRW~!Q![&}!g!h']#X#Y']~'`R{|'i}!O'i!Q!['o~'lP!Q!['o~'tPW~!Q!['o~'|SW~!O!P&w!Q!['w!g!h']#X#Y']~(_Oo~~(dPi~!_!`(g~(lOk~~(qPg~#r#s(t~(yOm~~)OPj~!_!`)R~)WOl~~)]Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!p$|!p!q)x!q!}$|#R#S$|#T#o$|~)}Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!f$|!f!g*j!g!}$|#R#S$|#T#o$|~*qVp~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~+]Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!q$|!q!r+x!r!}$|#R#S$|#T#o$|~+}Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!v$|!v!w,j!w!}$|#R#S$|#T#o$|~,qVr~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~-]Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!t$|!t!u-x!u!}$|#R#S$|#T#o$|~.PVq~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~.kWf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#U/T#U#o$|~/YXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#`$|#`#a/u#a#o$|~/zXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#g$|#g#h0g#h#o$|~0lXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#X$|#X#Y1X#Y#o$|~1`VU~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~1zXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#i$|#i#j2g#j#o$|~2lXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#`$|#`#a3X#a#o$|~3^Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#`$|#`#a3y#a#o$|~4QVV~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|~4lXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#f$|#f#g5X#g#o$|~5^Xf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#i$|#i#j5y#j#o$|~6OXf~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#X$|#X#Y6k#Y#o$|~6rVT~f~tu$|!O!P$|!P!Q$|!Q![$|!c!}$|#R#S$|#T#o$|",
  tokenizers: [0],
  topRules: {"Filter":[0,4]},
  tokenPrec: 211
})
